#!/usr/bin/env bash

if [[ -z "$1" ]]; then
   echo "Missing target filename argument!"
   exit 1
fi

if [[ -z "$2" ]]; then
   echo "Missing file template argument!"
   exit 1
fi

if [ ! -f ~/scripts/addfile_data/$2 ]; then
   echo "Invalid file template $2"
   exit 1
fi

cp ~/scripts/addfile_data/$2 $1
