#!/usr/bin/env bash

get_output() {
	echo -e "\e[1;34m# Repository\e[0m"

	echo -e "Default branch: \e[0;36m$(git default-branch)\e[0m"
	echo -e "Branches: $(git remote-branches | wc -l)"

	echo ""
	echo -e "\e[1;34m# Local Repo\e[0m"
	
	echo -e "Directory: \e[0;35m$(git directory)\e[0m"
	echo -e "Local branches: $(git local-branches | wc -l)"

	echo ""
	echo -e "\e[1;34m# Working State\e[0m"

	git -c color.ui=always logs -n 8
	echo ""
	git -c color.ui=always status -sb
}

get_output | less -r -F
