#!/usr/bin/env bash

top="▄▄"
bot="▀▀"
div=" "
fg_top=""
fg_bot=""
use_fg="false"

while getopts "ft:b:d:v:" opt; do
  case $opt in
	f) use_fg="true" ;;
    t) top="$OPTARG" ;;
    b) bot="$OPTARG" ;;
	d) div="$OPTARG" ;;
	v) top="$OPTARG" ; bot="$OPTARG" ;;
  esac
done

if [ $use_fg = "true" ]; then
	fg_top="$div$top"
	fg_bot="$div$bot"
fi

echo -e "$fg_top$div\e[90m$top$div\e[91m$top$div\e[93m$top$div\e[92m$top$div\e[96m$top$div\e[94m$top$div\e[95m$top$div\e[97m$top$div\e[0m"
echo -e "$fg_bot$div\e[30m$bot$div\e[31m$bot$div\e[33m$bot$div\e[32m$bot$div\e[36m$bot$div\e[34m$bot$div\e[35m$bot$div\e[37m$bot$div\e[0m"
